services:
  - type: web
    name: kkh-analysis-backend
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && uvicorn app:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PORT
        sync: false
      - key: FRONTEND_URL
        value: https://your-app.vercel.app
    healthCheckPath: /health

